language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y # webkit svg script xmlpatterns uitools multimedia webkitwidgets multimediawidgets
    - sudo apt-get update -qq

install:
    - sudo apt-get -y install qt55base qt55webkit qt55svg qt55script qt55xmlpatterns qt55tools qt55multimedia libxt-dev libpaper-dev
    - source /opt/qt*/bin/qt*-env.sh

script:
  - git clone https://github.com/qtproject/qt-solutions
  - cd qt-solutions/qtsingleapplication
  - qmake PREFIX=/usr
  - make -j$(nproc)
  - sudo make install
  - cd -
  - cd ..
  - git clone https://github.com/OpenBoard-org/OpenBoard-ThirdParty
  - cd OpenBoard-ThirdParty
  - cd freetype
  - qmake freetype.pro -spec linux-g++
  - make -j$(nproc)
  - cd ..
  - cd quazip
  -  qmake quazip.pro -spec linux-g++
  -  make -j$(nproc)
  -  cd ..
  -  cd xpdf/xpdf-3.04
  -  ./configure --with-freetype2-library="../../freetype/lib/linux" --with-freetype2-includes="../../freetype/freetype-2.6.1/include"
  - cd ..
  - qmake xpdf.pro -spec linux-g++
  - make -j$(nproc)
  - cd ..
  - cd ..
  - cd OpenBoard
  - qmake OpenBoard.pro CONFIG+=release PREFIX=/usr -spec linux-g++-64
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir install ; find appdir/
  - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps ; cp resources/images/OpenBoard.png appdir/usr/share/icons/hicolor/256x256/apps/ # FIXME: make install should have installed an icon there
  - mkdir -p appdir/usr/share/applications/ ; cp resources/linux/openboard.desktop appdir/usr/share/applications/ # FIXME: make install should have done that
  - mkdir appdir/usr/bin ; cp build/linux/release/product/OpenBoard appdir/usr/bin/openboard # FIXME: make install should have done that
  - cp -r appdir/home/*/build/*/OpenBoard/build/linux/release/product/library/* appdir/usr/bin/library/ # FIXME: https://github.com/OpenBoard-org/OpenBoard/issues/146
  - rm -rf appdir/home/ # FIXME: https://github.com/OpenBoard-org/OpenBoard/issues/146
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
# - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file OpenBoard*.AppImage https://transfer.sh/OpenBoard-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh OpenBoard*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
